-- ============================================================
-- Prototype v3 (credentialing 3.html): one payer list for Payers, Payer Submissions and the Credential Vault.
-- Updates the 13 existing payers to the v3 data and adds 8 more (21 in total).
-- Existing payer codes are kept (medicaid = Texas Medicaid / TMHP).
-- ============================================================

UPDATE payer SET name = 'BCBS TX', full_name = 'Blue Cross Blue Shield of Texas', category = 'Commercial', payer_type = 'PPO/HMO', color = '#1d4ed8', app_form = 'Ambetter Provider Set-up Form', integration = 'caqh', api_support = 'partial', caqh_participating = 1, portal_url = 'https://providers.bcbstx.com', avg_tat_days = 49, submission_method = 'caqh_roster', api_available = 0, api_vendor = 'Availity (claims only)', api_docs_url = NULL, submission_notes = 'Blue Cross Blue Shield of Texas (HCSC subsidiary). Pulls provider data from CAQH ProView. Enrollment via Availity Essentials or BCBSTX portal. No direct enrollment API.', sort_order = 1, active = 1 WHERE code = 'bcbs_tx';
UPDATE payer SET name = 'Aetna', full_name = 'Aetna (CVS Health)', category = 'Commercial', payer_type = 'PPO/HMO', color = '#7c2d12', app_form = 'CAQH + Aetna Provider Portal', integration = 'caqh', api_support = 'partial', caqh_participating = 1, portal_url = 'https://www.aetna.com/health-care-professionals.html', avg_tat_days = 52, submission_method = 'caqh_roster', api_available = 0, api_vendor = 'Availity + NaviNet', api_docs_url = NULL, submission_notes = 'CVS Health subsidiary. Uses CAQH ProView + Availity. Aetna Provider Portal for direct submissions. No public enrollment API.', sort_order = 3, active = 1 WHERE code = 'aetna';
UPDATE payer SET name = 'Cigna', full_name = 'Cigna Healthcare', category = 'Commercial', payer_type = 'PPO/HMO', color = '#065f46', app_form = 'CAQH + CignaForHCP', integration = 'caqh', api_support = 'portal', caqh_participating = 1, portal_url = 'https://cignaforhcp.cigna.com', avg_tat_days = 61, submission_method = 'caqh_roster', api_available = 0, api_vendor = 'CignaForHCP (portal)', api_docs_url = NULL, submission_notes = 'Enrollment via CignaForHCP portal + CAQH. API program exists for claims and eligibility only.', sort_order = 4, active = 1 WHERE code = 'cigna';
UPDATE payer SET name = 'UHC', full_name = 'UnitedHealthcare (UHG)', category = 'Commercial', payer_type = 'PPO/HMO', color = '#1e3a8a', app_form = 'CAQH + UHC Provider Portal', integration = 'caqh', api_support = 'full', caqh_participating = 1, portal_url = 'https://uhcprovider.com', avg_tat_days = 58, submission_method = 'caqh_roster', api_available = 1, api_vendor = 'UHC/Optum APIs', api_docs_url = 'https://developer.uhc.com', submission_notes = 'UHC/Optum has public developer APIs at developer.uhc.com — Provider Directory, Operations. Enrollment still goes through CAQH roster + UHC Provider Portal.', sort_order = 5, active = 1 WHERE code = 'uhc';
UPDATE payer SET name = 'Humana', full_name = 'Humana', category = 'Commercial', payer_type = 'PPO/HMO', color = '#15803d', app_form = 'CAQH + Availity', integration = 'availity', api_support = 'portal', caqh_participating = 1, portal_url = 'https://provider.humana.com', avg_tat_days = 64, submission_method = 'availity', api_available = 1, api_vendor = 'Availity + Humana Developer', api_docs_url = 'https://developers.humana.com', submission_notes = 'Humana developer portal has FHIR-based APIs for benefits, claims, and member data. Enrollment still goes through CAQH roster + Availity.', sort_order = 6, active = 1 WHERE code = 'humana';
UPDATE payer SET name = 'Anthem', full_name = 'Anthem (Elevance Health) BCBS', category = 'Commercial', payer_type = 'PPO/HMO', color = '#003DA5', app_form = 'CAQH + Availity', integration = 'availity', api_support = 'partial', caqh_participating = 1, portal_url = 'https://availity.com', avg_tat_days = 55, submission_method = 'availity', api_available = 1, api_vendor = 'Availity', api_docs_url = 'https://apigw.availity.com', submission_notes = 'Anthem is now ''Elevance Health''. 14 BCBS state plans. Primary channel is Availity Essentials + API Gateway for X12 and REST.', sort_order = 7, active = 1 WHERE code = 'anthem';
UPDATE payer SET name = 'Kaiser', full_name = 'Kaiser Permanente', category = 'Commercial (HMO)', payer_type = 'HMO', color = '#006BA6', app_form = 'Kaiser Provider Enrollment (internal)', integration = 'portal', api_support = 'portal', caqh_participating = 0, portal_url = 'https://providers.kaiserpermanente.org', avg_tat_days = 90, submission_method = 'portal_only', api_available = 0, api_vendor = 'Kaiser Provider Portal', api_docs_url = NULL, submission_notes = 'Closed network — Kaiser mostly employs physicians directly. External credentialing is limited; contact regional Kaiser office for details.', sort_order = 8, active = 1 WHERE code = 'kaiser';
UPDATE payer SET name = 'Molina', full_name = 'Molina Healthcare', category = 'Medicaid MCO', payer_type = 'Managed', color = '#0072BC', app_form = 'Molina Provider Application', integration = 'availity', api_support = 'portal', caqh_participating = 1, portal_url = 'https://provider.molinahealthcare.com', avg_tat_days = 72, submission_method = 'availity', api_available = 1, api_vendor = 'Availity', api_docs_url = 'https://apigw.availity.com', submission_notes = 'Multi-state Medicaid MCO. Uses Availity for most electronic transactions. Portal-based enrollment with roster support via CAQH.', sort_order = 9, active = 1 WHERE code = 'molina';
UPDATE payer SET name = 'Centene', full_name = 'Centene / Ambetter / WellCare', category = 'Medicaid MCO', payer_type = 'Managed', color = '#009999', app_form = 'Centene Provider Enrollment', integration = 'availity', api_support = 'portal', caqh_participating = 1, portal_url = 'https://provider.ambetter.centene.com', avg_tat_days = 68, submission_method = 'availity', api_available = 1, api_vendor = 'Availity', api_docs_url = 'https://apigw.availity.com', submission_notes = 'Centene operates Ambetter (marketplace), Fidelis NY, Superior TX, Peach State GA, WellCare, and others. Availity is primary channel for enrollment and operations.', sort_order = 10, active = 1 WHERE code = 'centene';
UPDATE payer SET name = 'WellCare', full_name = 'WellCare (Centene)', category = 'Medicare Advantage', payer_type = 'Medicare Advantage', color = '#005A9C', app_form = 'WellCare Provider Enrollment', integration = 'availity', api_support = 'portal', caqh_participating = 1, portal_url = 'https://wellcare.com/provider', avg_tat_days = 70, submission_method = 'availity', api_available = 1, api_vendor = 'Availity', api_docs_url = 'https://apigw.availity.com', submission_notes = 'WellCare is a Centene subsidiary focused on Medicare Advantage and Medicaid. Enrollment via Availity.', sort_order = 11, active = 1 WHERE code = 'wellcare';
UPDATE payer SET name = 'Superior', full_name = 'Superior HealthPlan (TX MCO)', category = 'Medicaid MCO', payer_type = 'Managed', color = '#0369a1', app_form = 'MCO App via Availity', integration = 'availity', api_support = 'portal', caqh_participating = 1, portal_url = 'https://www.superiorhealthplan.com/providers.html', avg_tat_days = 75, submission_method = 'availity', api_available = 1, api_vendor = 'Availity (Centene subsidiary)', api_docs_url = 'https://apigw.availity.com', submission_notes = 'Centene subsidiary covering Texas STAR, STAR+PLUS, CHIP. Uses Availity for enrollment and claims.', sort_order = 12, active = 1 WHERE code = 'superior';
UPDATE payer SET name = 'Medicare', full_name = 'Medicare (CMS)', category = 'Federal', payer_type = 'FFS', color = '#1e40af', app_form = 'CMS-855I (Individual) / CMS-855B (Group) / CMS-855O (Order)', integration = 'pecos', api_support = 'portal', caqh_participating = 0, portal_url = 'https://pecos.cms.hhs.gov', avg_tat_days = 60, submission_method = 'pecos', api_available = 0, api_vendor = 'PECOS', api_docs_url = 'https://data.cms.gov/provider-data/', submission_notes = 'PECOS is CMS''s official enrollment system — web portal only, no public enrollment API. Blue Button 2.0 FHIR API exists for claims data. ~$688 application fee.', sort_order = 15, active = 1 WHERE code = 'medicare';
UPDATE payer SET name = 'Medicaid TX', full_name = 'Texas Medicaid (TMHP)', category = 'State Medicaid', payer_type = 'FFS', color = '#0f766e', app_form = 'TMHP Provider Enrollment', integration = 'portal', api_support = 'portal', caqh_participating = 0, portal_url = 'https://www.tmhp.com', avg_tat_days = 92, submission_method = 'state_portal', api_available = 0, api_vendor = 'TMHP (state-specific)', api_docs_url = NULL, submission_notes = 'Texas Medicaid Healthcare Partnership. Required for Texas Medicaid participation. Portal-based enrollment with state-specific requirements.', sort_order = 17, active = 1 WHERE code = 'medicaid';

INSERT INTO payer (code, name, full_name, category, payer_type, color, app_form, integration, api_support, caqh_participating, portal_url, avg_tat_days, submission_method, api_available, api_vendor, api_docs_url, submission_notes, sort_order, pricing_category, pricing_mult) VALUES ('bcbs_il', 'BCBS IL', 'Blue Cross Blue Shield of Illinois', 'Commercial', 'PPO/HMO', '#1d4ed8', 'BCBSIL Provider Enrollment', 'caqh', 'partial', 1, 'https://providers.bcbsil.com', 51, 'caqh_roster', 0, 'Availity', NULL, 'Also an HCSC plan. CAQH roster + Availity for enrollment. Common BCBS plan nationwide.', 2, 'commercial', 1);
INSERT INTO payer (code, name, full_name, category, payer_type, color, app_form, integration, api_support, caqh_participating, portal_url, avg_tat_days, submission_method, api_available, api_vendor, api_docs_url, submission_notes, sort_order, pricing_category, pricing_mult) VALUES ('magellan', 'Magellan', 'Magellan Health', 'Behavioral Health', 'Managed', '#4a148c', 'Magellan Provider Enrollment', 'portal', 'portal', 1, 'https://www.magellanprovider.com', 80, 'portal_only', 0, 'Magellan Provider Portal', NULL, 'Behavioral health benefits manager (BHO). Portal-based enrollment + CAQH data. Used by many commercial payers for behavioral health carve-outs.', 13, 'commercial', 1);
INSERT INTO payer (code, name, full_name, category, payer_type, color, app_form, integration, api_support, caqh_participating, portal_url, avg_tat_days, submission_method, api_available, api_vendor, api_docs_url, submission_notes, sort_order, pricing_category, pricing_mult) VALUES ('carelon', 'Carelon', 'Carelon Behavioral Health (Elevance)', 'Behavioral Health', 'Managed', '#5e35b1', 'Carelon Provider Enrollment', 'availity', 'portal', 1, 'https://providers.carelon.com', 75, 'availity', 0, 'Availity + Carelon Portal', NULL, 'Formerly Beacon Health Options, now part of Elevance Health. Behavioral health carve-out for many commercial plans.', 14, 'commercial', 1);
INSERT INTO payer (code, name, full_name, category, payer_type, color, app_form, integration, api_support, caqh_participating, portal_url, avg_tat_days, submission_method, api_available, api_vendor, api_docs_url, submission_notes, sort_order, pricing_category, pricing_mult) VALUES ('medicare_adv', 'Medicare Advantage', 'Medicare Advantage (Various)', 'Medicare Advantage', 'Managed', '#1e3a8a', 'Varies by MA plan', 'caqh', 'portal', 1, NULL, 65, 'caqh_roster', 0, 'Varies (UHC, Humana, Aetna, Anthem, etc.)', NULL, 'Medicare Advantage plans are offered by private payers. Each MA plan (UHC MA, Humana MA, Aetna MA, Kaiser MA) has its own process — usually CAQH + their portal.', 16, 'medicare', 1);
INSERT INTO payer (code, name, full_name, category, payer_type, color, app_form, integration, api_support, caqh_participating, portal_url, avg_tat_days, submission_method, api_available, api_vendor, api_docs_url, submission_notes, sort_order, pricing_category, pricing_mult) VALUES ('medicaid_ca', 'Medi-Cal CA', 'California Medicaid (PAVE)', 'State Medicaid', 'FFS', '#0f766e', 'DHCS PAVE Application', 'portal', 'portal', 0, 'https://www.dhcs.ca.gov/provgovpart', 110, 'state_portal', 0, 'DHCS PAVE', NULL, 'California Medi-Cal uses PAVE (Provider Application and Validation for Enrollment). FHIR-based API in development as of 2024-2025.', 18, 'medicaid', 1);
INSERT INTO payer (code, name, full_name, category, payer_type, color, app_form, integration, api_support, caqh_participating, portal_url, avg_tat_days, submission_method, api_available, api_vendor, api_docs_url, submission_notes, sort_order, pricing_category, pricing_mult) VALUES ('medicaid_ny', 'Medicaid NY', 'New York Medicaid (eMedNY)', 'State Medicaid', 'FFS', '#0f766e', 'eMedNY Enrollment Application', 'portal', 'portal', 0, 'https://www.emedny.org', 100, 'state_portal', 0, 'eMedNY (CSC State Health)', NULL, 'New York State Medicaid enrollment through eMedNY. Portal-based with required training completion.', 19, 'medicaid', 1);
INSERT INTO payer (code, name, full_name, category, payer_type, color, app_form, integration, api_support, caqh_participating, portal_url, avg_tat_days, submission_method, api_available, api_vendor, api_docs_url, submission_notes, sort_order, pricing_category, pricing_mult) VALUES ('tricare', 'TRICARE', 'TRICARE (Military)', 'Federal', 'Managed', '#4a5568', 'TRICARE Provider Enrollment via Humana (East) or Health Net (West)', 'portal', 'portal', 1, 'https://www.tricare.mil/providers', 55, 'portal_only', 0, 'Humana Military (East) + Health Net Federal (West)', NULL, 'US military health benefits. East region administered by Humana Military, West region by Health Net Federal Services. Use their portals + CAQH data.', 20, 'commercial', 1);
INSERT INTO payer (code, name, full_name, category, payer_type, color, app_form, integration, api_support, caqh_participating, portal_url, avg_tat_days, submission_method, api_available, api_vendor, api_docs_url, submission_notes, sort_order, pricing_category, pricing_mult) VALUES ('va_ccn', 'VA CCN', 'VA Community Care Network', 'Federal', 'Managed', '#1b5e20', 'VA CCN Provider Application (via Optum or TriWest)', 'portal', 'portal', 1, 'https://www.va.gov/COMMUNITYCARE', 85, 'portal_only', 0, 'Optum (Regions 1-3) + TriWest (Regions 4-5)', NULL, 'VA Community Care Network for serving veterans. Administered by Optum in regions 1-3 and TriWest in regions 4-5.', 21, 'commercial', 1);
